### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by User11093** [knulii/1nstaMart#1]
can not get this work

ive obvs created a new .onion address and changed nginx conf but nothing ?

**Comment by knulii** [comment]
> can not get this work
> 
> ive obvs created a new .onion address and changed nginx conf but nothing ?

There could very well be some issues...

What OS are you running on? PHP version?
Are you using your own onion addy?
did you point torrc to the onion keys?

**Comment by User11093** [comment]
Ubuntu 22.04
PHP 8.1.27
and yes the the torrc is pointed to the correct onion keys

**Comment by knulii** [comment]
I have yet to get php8 to work correctly once installed. The messaging feature is broken. But it should still install
If you are choosing option 3 when you do run.sh, just replace the onion keys in the folder onions/onion1 with your new keys. 
and change the server_name in nginx/default
https://github.com/knulii/1nstaMart/blob/3990418e64915d17f50ec784ced7dff2fd49916a/nginx/default#L7

**Comment by User11093** [comment]
i have done this already but with no success

i will try again on php 7

**Comment by User11093** [comment]
Just a quick update ive still not been able to get this working on php 7

**Comment by User11093** [comment]
sorry to be a complete noob!! however im struggling to find where the config.app name is located so i can change the store name from 1nstaMark
